import { TravelRequest, Traveler } from './types';

export const MOCK_REQUESTS: TravelRequest[] = [
  {
    id: 'REQ-4829',
    employeeName: 'Marcus Sterling',
    role: 'Senior Engineer',
    avatar: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDojPkh_d0jfsH_0rbkHtZVUWg6kTBSs1fAAQ1jzz8tGcGlA00XdKZ-AtWKPsTbf1E1FWtNkl-FOVTBVBFXNym6Lf-RHBp5DRHQWTCt6u2oqNQfYygEnztmnpdUbAaVDtBuhFugZzjOwuE3K4oNpyOXJSz45Fa17S1ksRL4z77N6Ocayb1sRgu02NTwpk7qTJIvD0H6cqRJ8Hx6Dd8GfWJvlLGDtLB__TuwhGeP70MOP41fY5l7PhU6vwZ_5qSmMye7rFJUrVduY1SF',
    destination: 'Zurich, CH',
    dates: 'Nov 12 - Nov 18',
    nights: '6 nights',
    purpose: 'Tech Summit 2023',
    cost: '$4,250.00',
    status: 'PENDING',
    department: 'Engineering',
  },
  {
    id: 'REQ-4830',
    employeeName: 'Elena Rodriguez',
    role: 'Sales Director',
    avatar: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCb40Az0M6EXssj_T-xsX3ZukpEGlDLMj0VTD8vXVkke50vFY8puY3-yAWwgjDGICqBoFb3Pw_jGdx99VXD4YkgZG8d2_sNTisfjtjgNv4i8EQrIDRCAHc0s59geWBHHwOQTVM3XXWytquVRUXzmu5PBQg2HvZxLfFRQa-2RJlFT3_wkqSUrEwLZw7h9e1APfSLcMVm7WdIRGmyFUkNVvZl52wbBfKdVSmOTKpqv9AYfMzVjKlnIQoXbf0JAhP0tobHm-9s67Z-4le5',
    destination: 'Tokyo, JP',
    dates: 'Oct 24 - Oct 31',
    nights: '7 nights',
    purpose: 'Client Acquisition',
    cost: '$8,120.00',
    status: 'APPROVED',
    department: 'Sales & Marketing',
  },
  {
    id: 'REQ-4831',
    employeeName: 'Jameson Thorne',
    role: 'VP Product',
    avatar: 'https://lh3.googleusercontent.com/aida-public/AB6AXuADifMs8dhQ7krSDQYhyKsKweaM_dbqNaukF2dT-FAHPSU8pVrDP7nJPB6UThh9ULnJDyPzt6WJoRz9-Ed31DTnzecQ9NwPhOEbGxVhihr1vWkoU9JxlfUl9Heo3LK1BNNSWQsK00uEJVjDCmB2EN86V_COffPF6VKCQU-UMNHQzC2JBzjQUSIJFQC3tJ-9bv_XL5m7SZqxQv31Dq9_KlUGUre7IB_PtiH-YvYsv3iyYKWzUcAsJ6X1bwI9MonVhzJBMGJ8hpCSh1uF',
    destination: 'New York, US',
    dates: 'Nov 02 - Nov 05',
    nights: '3 nights',
    purpose: 'Board Meeting',
    cost: '$2,800.00',
    status: 'PENDING',
    department: 'Executive',
  },
  {
    id: 'REQ-4832',
    employeeName: 'Sarah Chen',
    role: 'Design Lead',
    avatar: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAxHJQkcJmTYyqzSYkIH09mzA6L7pX148E-NjwaXNJOd9ZCV1by0ltVJLEHr3NE4sTeGe6ro6nik7i07poQh7KBsh0BIGg6N0da5_XDzZqupzxNhBP6fCcgXo7aOTRJ7hQTJmiz1c5t7pQ8blJxj2RCmuUL3mbIdnGQcGrERvOzBdddR9yycV2BbKo8Ycps9megyHudGfHHuRCpwvA2yWelkaZquKUzfUiUKhhyIv2eYUCn97rQNt-EVosm11EmzThlNCcablIAAM5x',
    destination: 'London, UK',
    dates: 'Dec 01 - Dec 10',
    nights: '9 nights',
    purpose: 'Offsite Workshop',
    cost: '$5,650.00',
    status: 'DENIED',
    department: 'Product Design',
  },
];

export const MOCK_TRAVELERS: Traveler[] = [
  {
    id: 'ST-99210',
    name: 'Julianne Devis',
    role: 'Product Design Lead',
    avatar: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCVWzSbx8RjtblDTh8kl97O8LuU7nFOhHectHWcftPuTSUblk0I5T3wp28xhB4XwamRdcBsyBMDQpyIiDGdpCfY97lhL3MO7uOSML3xwlhqCa2vlZ1GRbcCzak0grqgl3TouTuw072QVotZfzuZaM_G9zi6C_pJ-hg3xVHX96UPqxKlGzYyunSSixtBaTsnFeDd5c3ef1i1kIPbA-ZwdWLn3qunKn2BeBuXVS-uQPredL8VLuhlbKAwx_SUGHs16OMst9-Ih5ZJKK_Z',
    status: 'Compliant',
    preferences: ['Aisle Seat', 'Vegetarian', 'Marriott Bonvoy Gold'],
    passportStatus: 'Valid',
    visaStatus: 'Valid',
    visaRegion: 'US',
  },
  {
    id: 'ST-99214',
    name: 'Marcus Chen',
    role: 'Senior DevOps Engineer',
    avatar: 'https://lh3.googleusercontent.com/aida-public/AB6AXuB2ueiXhQQJi7mgPTc3NU0ofJ14rj-M2FSL5r6VZ5xnEotpu0uysLWjqbtxgw0Kp7AFfMMEnVCHRWOSxSqLEjEH7zkfe7pp7sgt1MGqqW06OQ45WxiYHz2eyMm3xXZf8JT1Mnxwi0Q7XyN9P3sE0hH_eH0AwFMA5OPjak_4X2sxNS7yhEepsEzD-5YZB0jRJc05tOxGYYMdCOnSK-HLWcT5hXsevAlFqx25IZKp1KkCMPDF7KK7JlNp0slS5_lQrpP_fvKSRBNFoWw4',
    status: 'Pending Update',
    preferences: ['Window Seat', 'Hilton Honors'],
    passportStatus: 'Expiring soon',
    visaStatus: 'Valid',
    visaRegion: 'UK',
  },
  {
    id: 'ST-99221',
    name: 'Sarah Bennett',
    role: 'Global Sales Director',
    avatar: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBewlCz_9zUObyvw071KizkKVl6DX2ZZZ2f4g-yL4K1mIBHBhU2fG5jV9XJBiYwkt7vi-5mQPechwDN09qu41knF2MinFdvMtvZ1mE7SLwDnr4kckoYm0BZjBa8ZocgOdH2hVfHrIIN18ZtUhGSO17IgTgrDwEcC9pyotXAPmjOUhWb9SYoPq703p2c8wu4hvc6V-aQx1UaMcy1H3vhfKUJHYA9X6fwk9ecHGVkWxMpqRxbHp5tp504g5lhHG8d-aZi0pmsA44qLEmu',
    status: 'Compliant',
    preferences: ['Business Class', 'Lounge Access', 'Delta Diamond'],
    passportStatus: 'Valid',
    visaStatus: 'Active',
    visaRegion: 'Global Entry',
  },
  {
    id: 'ST-99232',
    name: 'Liam Anderson',
    role: 'Lead Data Analyst',
    avatar: 'https://lh3.googleusercontent.com/aida-public/AB6AXuD1faNoZLTuCaT8fQXFWw_ql3d_muwhNdqWEmeYpacg4xZWMg19Bth7Ast2_582syX148_IgAmukKEc0g34qnDAsqJ1-D4-3ICreH1P_sjL46QHMLipMs35wP6wRnvU8rakiZzDeGpt2gOhS5mWuKnfBHHYCaDg1dwT8F5W1jCukIw6D-qyfBzBnpeM21nSr7-Th590NZnvSq6JQQqdeSnfouNCypS5dpv8js_MBCtaHe4uPG7WBCIW2eenOdvkF4gW8gBohITRL3P-',
    status: 'Compliant',
    preferences: ['Low Floor', 'Car Rental Req.'],
    passportStatus: 'Valid',
    visaStatus: 'Valid',
  },
];
